[package]
name = "chap01"
version = "0.1.3"
authors = ["athevenot"]
edition = "2018"
description = "Some algorithms for NPL100 training"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
